spring:
  application:
    name: ftp-service
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 9999

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

ftp:
  local:
    resource:
      path: c:/ftp_files/
  remote:
    resource:
      path: /upload
  server:
    user:
      name: foo
      pwd: pass
    host:
      name: localhost
      port: 22

logging:
  level:
    org:
      springframework: TRACE
    com: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

